// Laravel and React/React/src/Pages/Home.js
import React from 'react'
import Header from './Header'
const Home=()=>{
    return(
    
      <div>
<div className="bgimage">
<Header/>
        <div className="text">
        <h3>Laravel • Api • React</h3>
        <h1>~Knowledge is power~</h1>
        <h2>Stay Home &lt;|&gt; Stay Safe</h2>
          <button id="buttonone" onClick={(e) => {e.preventDefault();window.location.href='/Login';
      }}>
        Login
      </button>
          <div className="dropdown">
            <button className="buttontwo">
              Sign-Up </button>
            <div>
              <a href="/Admin_signup">As ADMIN</a>
              <a href="/User_signup">AS User</a>
            </div>
          </div>
        </div>
      </div>
</div>
);
}

export default Home;

// Laravel and view/enkaizen_task_vue/src/components/Home.vue
<template>
 <div class="bgimage">
    <Header/>
     <div class="text">
        <h3>SEARCH • PARK • RELAX</h3>
        <h1>Cashless Parking Anywhere</h1>
        <h2>DON'T PARK ON STREET, USE PARKIT</h2>
     <router-link :to="{ path: '/Login' }"><button id="buttonone">Login</button></router-link>
		<div class="dropdown">
        <button class="buttontwo">
          Sign-Up </button>
          <div>
            
              <router-link to="/Signup_admin">Admin_signup</router-link>
              <router-link to="/Signup_user">User_Signup</router-link>
            
          </div>
       
      </div>
    </div>
 </div>
</template>

<script>
import Header from './Header.vue'

export default {
  
    name:'Home',
     components: {
    Header
  }
}
</script>
